### ISSUE TITLE
각자 맡아서 진행한 번역들의 리스트를 취합해주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by SungSubKim** [18-2-SKKU-OSS/2018-2-OSS-L3-2-#24]
각자의 진행한 번역들을 페이지에 정리하고자 합니다.
자신이 진행한 번역들의 이름을 적어주시면 감사하겠습니다.

**Comment by wantyouring** [comment]
counting sort
radix sort
shell sort
selection sort
depth-first search

이렇게 번역완료했습니다!

**Comment by Kim-Hwan** [comment]
Shuffle 
Shunting Yard
Simulated annealing 
번역 완료했습니다!

SIngle-source shortest paths

**Comment by SungSubKim** [comment]
취합 완료하겠습니다 이슈 닫겠습니다
