### ISSUE TITLE
저희 이제 메인 readme 파일도 번역을 시작해야 할거 같네요

### ISSUE THREAD

**Issue by zzunny97** [18-2-SKKU-OSS/2018-2-OSS-L3-2-#28]

**Comment by SungSubKim** [comment]
제가 page설정을 건드리느라 readme파일을 변형시켜놓았습니다. 그 부분에 대해서 롤백을 하고 번역을 시도해보겠습니다. 감사합니다.

**Comment by SungSubKim** [comment]
가능하다면 번역을 제가 진행해도 될까요?
아님 양이 많으니 분할하여 번역을 진행해도 될듯 합니다.

**Comment by zzunny97** [comment]
절반씩 나눠서 하면 괜찮을거 같네요. 근데 저희 메인 readme가 어디있는지 잘 안보이네요.
먼저 일부 진행해주시면 커밋 내역 보고 나머지 하겠습니다.

**Comment by SungSubKim** [comment]
README-en.markdown이라는 파일로 복원하였고 앞부분에 대하여 먼저 번역 진행하겠습니다.

**Comment by SungSubKim** [comment]
앞부분 반절 번역 진행하였고 뒷부분 진행하여주시면 감사하겠습니다.

**Comment by wantyouring** [comment]
네 알겠습니다. 감사합니다

**Comment by SungSubKim** [comment]
김환이 잔여분 번역완료하였습니다 수고하셨습니다.
